### ISSUE TITLE
[1.21.1] World Invisible, "Player moved wrongly!"

### ISSUE THREAD

**Issue by Maloonkey** [cheyao/minecraft-plugin#1]
As title says, creating a new world with the 2D Minecraft world type produces no visible world, trying to move or just standing still spams the log with "Player moved wrongly!" and warps me back into place.

Fabric Loader 0.16.7, only Fabric API and 2D Minecraft installed.

![javaw_XUqeSJ3NrU](https://github.com/user-attachments/assets/034969ce-c743-42c5-8105-85f21491410f)

**Comment by cheyao** [comment]
Huh that's weird! Do you mind giving me your full logs? And are you playing on Minecraft 1.12.1? Everything works fine for me

**Comment by Maloonkey** [comment]
Yes, I'm using 1.21.1. This is really strange but I decided to do a completely fresh install and the issue went away. I even re-added mods that I disabled thinking they were the issue and it's fine now.

Here is a log of one of the erroneous runs, anyway.

[2024-10-18-4.log](https://github.com/user-attachments/files/17428658/2024-10-18-4.log)

Should I close the issue?

**Comment by cheyao** [comment]
Oh wow, that is really strange, it's probably because the world presets are still experimental. 

But anyways I'll still take a look at the logs. 

Feel free to reopen a issue if anything happens!
