### ISSUE TITLE
I want to use the mod on a server,

### ISSUE THREAD

**Issue by Zhado8** [cheyao/minecraft-plugin#3]
But the world generates an normal, how to fix this?
![image](https://github.com/user-attachments/assets/07d67821-0a77-4078-a385-e2bd65015858)

**Comment by cheyao** [comment]
You should set `level-type` to `flat-minecraft\:paper_world`. The names are weird since Minecraft doesn't allow numbers in the tags, and I couldn't think of a better name :P

For the moment the servers don't work (You will get a client moved too quickly error) I'll fix it when I'm free

**Comment by cheyao** [comment]
Or you can install a mod like gottagofast to disable the serverside speed limit

**Comment by cheyao** [comment]
I'll close it :+1:
