### ISSUE TITLE
The 2D world keeps generating 3D land (Beyond the normal 3 blook area you normally have)

### ISSUE THREAD

**Issue by ZaneFlynt01** [cheyao/minecraft-plugin#4]
I was playing in a world I made in 2D but a bit away from spawn I end up finding the land still goes 3D. At first I thought it was just an issue because I originally started with a bunch of mods, but later on where the only other mods were rendering mods like Sodium and Iris and a mod to remove durability (added after I found this out), it still generated 3D terrain a while from spawn.

**Comment by Zhado8** [comment]
i think its likely its the  durability no clue why tho,
i had similar issues with other mods
i can confirm it works with these mods on 1,21,1 
![image](https://github.com/user-attachments/assets/648c9214-c3ef-4aa5-bb24-e024bcd44e26)

**Comment by Zhado8** [comment]
Oh and if you are adding more mods along the 2dMinecraft mod to you´re world, i would insist you take frequent world backups

**Comment by cheyao** [comment]
Hey! I've just tried to reproduce this bug by going a long distance from spawn, but the mod works completely fine for me (I've got `ferritecore` and `sodium` installed).

Can you provide more details, for example your seed, log files and how far you traveled?

Thanks
